spring.application.name=library

# ===============================
# CONFIGURACIÓN DE POSTGRESQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURACIÓN DE HIBERNATE / JPA
# ===============================
# Esto muestra en la consola el código SQL que Spring escribe por ti (muy útil para depurar)
spring.jpa.show-sql=true

# ¡La magia ocurre aquí! 'update' lee tus clases Entity y crea/actualiza las tablas en la BD automáticamente
spring.jpa.hibernate.ddl-auto=update

# Opcional pero recomendado: Le dice a Hibernate que optimice el SQL específicamente para PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect